### ISSUE TITLE
How to get all lines that pass by a stop

### ISSUE THREAD

**Issue by danito** [helldog136/pystibmivb#5]
Hi,

seems it's not so easy to get all lines that pass by a certain stops as only lines that are actively riding are shown in PassingTimeByPoint and /PointDetail/{ids} doesn't return this.
If you want to get all the lines that pass by a stop, you need to check /PointByLine/{ids} for every line if it ever passes by the stopId.

**Comment by helldog136** [comment]
True it was not easy to get a clear list of lines passing at a certain stop. I add this in 1.2.0
