### ISSUE TITLE
make max_passages great again

### ISSUE THREAD

**Issue by helldog136** [helldog136/pystibmivb#9]
the max_passage logic has to evolve because i'm not satisfied of it.
I want this to specify the "x" next passages of the stop but it doesn't do that at the moment.
Will also default it to None, None saying "no limit"

**Comment by danito** [comment]
As the API returns 2 expectedArrivalTime per line per stop_id, do you want to add more theoretical expectedArrivalTimes from the timetable and limit this with max_passage?
Or do you want to limit the results for a certain stop_id which has a lot of lines passing?

**Comment by helldog136** [comment]
I think that i'll go with:
1) Get the passages for all the stop_ids relative to the stop_name
    Complete these passages with theoretical passages in case the API returns nothing for this stop_id
2) Sort these passage by closest arrival time
3) limit the length of this list to max_passage items
